FROM docker.io/library/debian@sha256:a546ef4dfa549a4b1a17777b4375c18773963e927f5cda378f2d105a07f1fc15 AS builder

FROM --platform=${TARGETPLATFORM} scratch

ARG TARGETPLATFORM
ARG VARIANT

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /tmp /tmp
COPY --from=builder /dev /dev

ENV v2ray.location.asset=/opt/v2ray/share

COPY ./ /opt/v2ray/

CMD ["/opt/v2ray/bin/v2ray"]
