FROM gcr.io/distroless/static-debian11@sha256:0f29b9f9818cc0371cae6cef4723f0406184547deeb3aee0db831aeea4527605 AS builder

FROM --platform=${TARGETPLATFORM} scratch

ARG TARGETPLATFORM
ARG VARIANT

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /tmp /tmp
COPY --from=builder /dev /dev

ENV v2ray.location.asset=/opt/v2ray/share

COPY ./ /opt/v2ray/

CMD ["/opt/v2ray/bin/v2ray"]
